export const products = [
    {
        id: "1",
        name: "Haier AC Unit 1",
        tag: "Only This Week",
        title: "Get the best quality products at the lowest prices",
        description: "A different kind of AC store",
        image: "/placeholder.svg?height=200&width=300",
        details:
            "This is a high-efficiency AC unit designed for optimal cooling in medium-sized rooms. It features smart temperature control and energy-saving modes. Perfect for residential use.",
        price: "$599.99",
        features: [
            "Energy-efficient cooling",
            "Smart temperature control",
            "Quiet operation",
            "Easy installation",
            "Remote control included",
        ],
    },
    {
        id: "2",
        name: "Haier AC Unit 2",
        tag: "Only This Week",
        title: "Get the best quality products at the lowest prices",
        description: "A different kind of AC store",
        image: "/placeholder.svg?height=200&width=300",
        details:
            "A powerful AC unit suitable for larger spaces, offering rapid cooling and advanced air purification. Ideal for commercial or large residential areas.",
        price: "$749.99",
        features: [
            "Rapid cooling technology",
            "Advanced air purification",
            "Large area coverage",
            "Durable build quality",
            "Wi-Fi connectivity",
        ],
    },
    {
        id: "3",
        name: "Haier AC Unit 3",
        tag: "Only This Week",
        title: "Get the best quality products at the lowest prices",
        description: "A different kind of AC store",
        image: "/placeholder.svg?height=200&width=300",
        details:
            "Compact and efficient, this AC unit is perfect for small apartments or bedrooms. It offers a sleek design and user-friendly controls.",
        price: "$449.99",
        features: [
            "Compact design",
            "User-friendly interface",
            "Low power consumption",
            "Sleep mode for comfort",
            "Easy to clean filters",
        ],
    },
    {
        id: "4",
        name: "Haier AC Unit 4",
        tag: "Only This Week",
        title: "Get the best quality products at the lowest prices",
        description: "A different kind of AC store",
        image: "/placeholder.svg?height=200&width=300",
        details:
            "An all-weather AC unit with heating and cooling capabilities. Provides year-round comfort with intelligent climate control.",
        price: "$899.99",
        features: [
            "Heating and cooling functions",
            "Intelligent climate control",
            "Outdoor unit included",
            "Weather-resistant design",
            "Programmable timer",
        ],
    },
    {
        id: "5",
        name: "Haier AC Unit 5",
        tag: "Only This Week",
        title: "Get the best quality products at the lowest prices",
        description: "A different kind of AC store",
        image: "/placeholder.svg?height=200&width=300",
        details:
            "This model focuses on silent operation, making it ideal for bedrooms or offices where noise reduction is critical. Enjoy cool air without disturbance.",
        price: "$629.99",
        features: [
            "Ultra-quiet operation",
            "Optimized airflow",
            "Remote temperature sensing",
            "Child lock feature",
            "Modern aesthetic",
        ],
    },
    {
        id: "6",
        name: "Haier AC Unit 6",
        tag: "Only This Week",
        title: "Get the best quality products at the lowest prices",
        description: "A different kind of AC store",
        image: "/placeholder.svg?height=200&width=300",
        details:
            "A robust AC unit built for durability and consistent performance in challenging environments. Features enhanced filtration for cleaner air.",
        price: "$799.99",
        features: [
            "Heavy-duty construction",
            "Enhanced air filtration",
            "Self-cleaning function",
            "Power surge protection",
            "Long lifespan",
        ],
    },
    {
        id: "7",
        name: "Haier AC Unit 7",
        tag: "Only This Week",
        title: "Get the best quality products at the lowest prices",
        description: "A different kind of AC store",
        image: "/placeholder.svg?height=200&width=300",
        details:
            "Designed for smart homes, this AC unit integrates seamlessly with popular voice assistants and smart home ecosystems for effortless control.",
        price: "$679.99",
        features: [
            "Smart home integration",
            "Voice control compatible",
            "Energy usage monitoring",
            "Customizable schedules",
            "Over-the-air updates",
        ],
    },
    {
        id: "8",
        name: "Haier AC Unit 8",
        tag: "Only This Week",
        title: "Get the best quality products at the lowest prices",
        description: "A different kind of AC store",
        image: "/placeholder.svg?height=200&width=300",
        details:
            "An eco-friendly AC unit that uses R32 refrigerant, reducing its environmental impact while providing powerful cooling. Ideal for conscious consumers.",
        price: "$719.99",
        features: [
            "Eco-friendly refrigerant",
            "Reduced carbon footprint",
            "High cooling capacity",
            "Anti-corrosion coating",
            "Diagnostic display",
        ],
    },
]
